version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "python main.py"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - my_network
  
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgis/postgis:14-master
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
   
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network: